# -*- coding: utf-8 -*-
"""
Page-level content per language. Original copy preserved verbatim.
Each page id maps to: hero img, title, subtitle, eyebrow, body paragraphs,
SEO title/description, and per-page image set (6 images each).
Images are file basenames under /assets/img/<folder>/.
"""

# Image pools (client's real photos only)
VENUE = [f"venue-{i:02d}" for i in range(1, 16)]      # 01..15
GAL   = [f"gallery-{i:02d}" for i in range(1, 34)]    # 01..33

# Curated 6-image sets per page (only real client photos, no orphans)
IMG = {
    "home":        ["venue-01","venue-02","venue-05","venue-12","gallery-13","venue-03"],
    "okalarre":    ["venue-03","venue-09","venue-15","gallery-08","venue-14","gallery-07"],
    "celebraciones":["venue-08","gallery-21","venue-10","gallery-28","venue-12","gallery-23"],
    "bodas":       ["gallery-10","gallery-20","gallery-19","venue-06","gallery-31","venue-05"],
    "comuniones":  ["venue-11","venue-10","gallery-15","gallery-33","gallery-16","gallery-27"],
    "eventos":     ["gallery-28","gallery-29","gallery-30","gallery-31","gallery-32","gallery-24"],
    "empresa":     ["venue-12","gallery-22","gallery-03","venue-02","venue-13","gallery-09"],
    "espacios":    ["venue-01","venue-12","venue-13","venue-02","gallery-27","venue-04"],
    "gastronomia": ["gallery-01","gallery-14","gallery-02","gallery-06","gallery-25","gallery-26"],
    "localizacion":["venue-14","gallery-08","venue-03","venue-15","venue-01","venue-02"],
    "contacto":    ["venue-15","venue-01","venue-02","venue-05","venue-12","venue-03"],
    "faq":         ["venue-12","venue-02","venue-05","venue-04","gallery-13","venue-08"],
    "galeria":     GAL,
}

# Hero image per page (full-bleed)
HERO = {
    "home":"gallery-09","okalarre":"venue-03","celebraciones":"venue-08","bodas":"gallery-21",
    "comuniones":"venue-10","eventos":"gallery-28","empresa":"venue-12","espacios":"venue-01",
    "gastronomia":"gallery-26","galeria":"gallery-16","localizacion":"venue-14",
    "faq":"venue-02","contacto":"venue-15",
}

# Alt text per language for the 6-image sets (descriptive, SEO)
def alt(lang, page, i):
    base = {
        "es":"Finca Okalarre, bodas y eventos en plena naturaleza en Bera, Navarra",
        "eu":"Finca Okalarre, ezkontzak eta ekitaldiak naturan, Bera, Nafarroa",
        "fr":"Finca Okalarre, mariages et événements en pleine nature à Bera, Navarre",
        "en":"Finca Okalarre, weddings and events in pure nature in Bera, Navarre",
    }[lang]
    return f"{base} — {i}"

# -------------------------------------------------------------------- PAGES
# Each entry: title (H1), eyebrow, sub (lead), body = list of paragraphs.
PAGES = {

"okalarre": {
 "es":{"seo_t":"Okalarre — Finca para bodas y eventos en Bera, Navarra | 15 años de experiencia",
       "seo_d":"Un excepcional enclave natural en el valle del Baztan-Bidasoa. Privacidad total, exteriores de ensueño y 15 años de experiencia celebrando momentos únicos.",
       "eyebrow":"El lugar","title":"Un rincón único en el valle encantado",
       "sub":"Vistas maravillosas, tranquilidad absoluta y aire puro en las alturas del Baztan-Bidasoa.",
       "body":[
         "Okalarre es un excepcional enclave natural en las alturas del valle encantado del Baztan-Bidasoa. Una construcción única con una gran terraza, jardín y un mirador envidiable sobre el valle, donde todos los detalles están cuidados.",
         "Solo la privacidad, la singularidad y la tranquilidad de nuestro rincón te garantizan el éxito de tu celebración. Aquí celebramos un único evento al día: el día es enteramente vuestro, sin prisas y sin límite de horario.",
         "15 años de experiencia avalan un proyecto donde los límites solo los pones tú. Ven, cuéntanos cómo lo imaginas y nosotros pondremos todo el cariño y la dedicación que mereces."],
       },
 "eu":{"seo_t":"Okalarre — Ezkontza eta ekitaldietarako finca Beran, Nafarroa",
       "seo_d":"Baztan-Bidasoa haraneko paraje natural paregabea. Erabateko pribatutasuna, ametsetako kanpoaldeak eta 15 urteko esperientzia.",
       "eyebrow":"Lekua","title":"Txoko paregabea harana sorginduan",
       "sub":"Ikuspegi zoragarriak, erabateko lasaitasuna eta aire garbia Baztan-Bidasoaren gailurretan.",
       "body":[
         "Okalarre Baztan-Bidasoa harana sorginduaren gailurretan dagoen paraje natural paregabea da. Terraza handia, lorategia eta haranaren gaineko begiratoki bikaina dituen eraikin berezia, non xehetasun guztiak zainduta dauden.",
         "Gure txokoaren pribatutasunak, berezitasunak eta lasaitasunak zure ospakizunaren arrakasta bermatzen dute. Egunean ekitaldi bakarra egiten dugu: eguna zuena da osorik, presarik eta ordutegi mugarik gabe.",
         "15 urteko esperientziak babesten du proiektu hau, non mugak zuk soilik jartzen dituzun. Etorri, kontaiguzu nola irudikatzen duzun eta merezi duzun maitasun eta gogo guztia jarriko dugu."],
       },
 "fr":{"seo_t":"Okalarre — Domaine pour mariages et événements à Bera, Navarre",
       "seo_d":"Une enclave naturelle exceptionnelle dans la vallée du Baztan-Bidassoa. Intimité totale, extérieurs de rêve et 15 ans d'expérience.",
       "eyebrow":"Le lieu","title":"Un coin unique dans la vallée enchantée",
       "sub":"Des vues magnifiques, un calme absolu et un air pur sur les hauteurs du Baztan-Bidassoa.",
       "body":[
         "Okalarre est une enclave naturelle exceptionnelle dans les hauteurs de la vallée enchantée du Baztan-Bidassoa. Une construction unique avec une grande terrasse, un jardin et un belvédère enviable sur la vallée, où tous les détails sont soignés.",
         "L'intimité, la singularité et le calme de notre coin sont un gage de réussite pour votre événement. Nous ne célébrons qu'un seul événement par jour : la journée est entièrement à vous, sans hâte et sans limite d'horaire.",
         "15 ans d'expérience garantissent un projet où vous êtes le seul à fixer les limites. Venez nous raconter comment vous l'imaginez et nous y mettrons tout le soin et le dévouement que vous méritez."],
       },
 "en":{"seo_t":"Okalarre — Wedding & event estate in Bera, Navarre | 15 years of experience",
       "seo_d":"An exceptional natural enclave in the Baztan-Bidasoa valley. Total privacy, dreamlike outdoor spaces and 15 years of experience celebrating unique moments.",
       "eyebrow":"The place","title":"A unique corner in the enchanted valley",
       "sub":"Wonderful views, absolute calm and pure air on the heights of the Baztan-Bidasoa.",
       "body":[
         "Okalarre is an exceptional natural enclave on the heights of the enchanted Baztan-Bidasoa valley. A unique building with a large terrace, a garden and an enviable viewpoint over the valley, where every detail is cared for.",
         "The privacy, singularity and tranquillity of our corner guarantee the success of your celebration. We host a single event per day: the day is entirely yours, unhurried and with no time limit.",
         "15 years of experience back a project where you alone set the limits. Come and tell us how you imagine it, and we'll bring all the care and dedication you deserve."],
       },
},

"bodas": {
 "es":{"seo_t":"Bodas en Navarra — Finca Okalarre | Bodas en plena naturaleza, Bera-Bidasoa",
       "seo_d":"Tu boda como la imaginas, en un lugar único y exclusivo para vosotros, sin límite de horario. Bodas especiales y originales en plena naturaleza en Okalarre.",
       "eyebrow":"Celebraciones","title":"Una boda única",
       "sub":"Tu boda, como tú la imaginas — en un lugar único y exclusivo para vosotros.",
       "body":[
         "Disfrutar preparando los preparativos de la boda es fundamental para que también puedas disfrutar de uno de los días más importantes de tu vida. Romántica, tradicional, innovadora, vintage, con molinillos de papel o rosas blancas, convencional, tipo cóctel, medieval, inolvidable, original, simpática, con niños, civil, sencilla, en sidecar o a caballo, con carpa, entrañable, otoñal o calurosa, íntima… cómo tú quieras, cómo tú lo sientas. Si tienes una idea aproximada de cómo quieres que sea tu boda y la sigues hasta el final, será un día inolvidable. ¡Ven y cuéntanosla! Nosotros pondremos todo el cariño y dedicación que mereces.",
         "En el cuidado servicio de restauración de Okalarre, prestado mediante caterings de reconocido prestigio, caben todo tipo de estilos: tradicional, innovador, con contrastes… para conseguir una elaboración personalizada y esmerada.",
         "Ven y disfruta de tu boda en un lugar único y exclusivo para vosotros sin límite de horario."],
       },
 "eu":{"seo_t":"Ezkontzak Nafarroan — Finca Okalarre | Ezkontzak naturan, Bera-Bidasoa",
       "seo_d":"Zure ezkontza irudikatzen duzun bezala, zuentzat soilik den leku paregabean, ordutegi mugarik gabe.",
       "eyebrow":"Ospakizunak","title":"Paregabeko ezkontza",
       "sub":"Zure ezkontza, irudikatzen duzun bezala — zuentzat soilik den leku paregabean.",
       "body":[
         "Ezkontzaren antolaketa-lanekin gozatzea berebizikoa da zure bizitzako egunik garrantzitsuenetakoa izango den horretan ere gozatu ahal izateko. Erromantikoa, tradizionala, berritzailea, vintagea, paperezko haize-errotatxoduna edo arrosa zuriduna, konbentzionala, koktel modukoa, Erdi Aroan girotua, ahaztezina, originala, alaia, haurrei tokia egingo diena, zibila, soila, sidekarrean edo zaldizkoa, karpaduna, maitagarria, udazken girokoa edo beroa, intimoa… zuk nahi bezalakoa, sentitzen duzun modukoa. Zure ezkontza nolakoa izatea nahi duzun zantzuren bat hartuta bazaude, bukaera arte eutsi eta egun ahaztezina izango da. Etorri eta kontaiguzu! Merezi dituzun maitasuna eta gogoa jarriko ditugu.",
         "Okalarreren sukaldaritza zerbitzu zainduak, prestigio handiko catering bidez emandakoak, orotariko estiloak lantzen ditu: tradizionala, berritzailea, kontrasteduna… Horrela elaborazio pertsonalizatu eta zaindua eskaintzeko.",
         "Etorri eta gozatu zure ezkontzaz zuentzat soilik den leku paregabean, ordutegi mugarik gabe."],
       },
 "fr":{"seo_t":"Mariages en Navarre — Finca Okalarre | Mariages en pleine nature, Bera-Bidassoa",
       "seo_d":"Votre mariage comme vous l'imaginez, dans un lieu unique et exclusif rien que pour vous, sans limite d'horaire.",
       "eyebrow":"Célébrations","title":"Un mariage unique",
       "sub":"Votre mariage, comme vous l'imaginez — dans un lieu unique et exclusif rien que pour vous.",
       "body":[
         "Passer d'agréables moments avec les préparatifs du mariage est essentiel pour que vous profitiez d'un des jours les plus importants de votre vie. Romantique, traditionnel, innovateur, vintage, avec des moulins à vent en papier ou des roses blanches, conventionnel, de type cocktail, médiéval, inoubliable, original, sympathique, avec des enfants, civil, simple, en sidecar ou à cheval, avec chapiteau, attachant, automnal ou chaleureux, intime… comme vous le voulez, comme vous le sentez. Si vous avez une idée approximative sur la manière d'organiser votre mariage et que vous la suivez jusqu'au bout, ce sera une journée inoubliable. Venez nous en parler ! Nous y mettrons notre cœur et le dévouement que vous méritez.",
         "Dans le service de restauration soigné d'Okalarre, assuré par des traiteurs de renom, tous les styles trouvent leur place : traditionnel, innovateur, avec des contrastes… pour obtenir une élaboration personnalisée et soignée.",
         "Venez profiter de votre mariage dans un lieu unique et exclusif rien que pour vous, sans limite d'horaire."],
       },
 "en":{"seo_t":"Weddings in Navarre — Finca Okalarre | Weddings in pure nature, Bera-Bidasoa",
       "seo_d":"Your wedding the way you imagine it, in a unique place exclusively for you, with no time limit. Special, original weddings in pure nature at Okalarre.",
       "eyebrow":"Celebrations","title":"A unique wedding",
       "sub":"Your wedding, the way you imagine it — in a place that is unique and exclusively yours.",
       "body":[
         "Enjoying the wedding preparations is essential so that you can also enjoy one of the most important days of your life. Romantic, traditional, innovative, vintage, with paper pinwheels or white roses, conventional, cocktail-style, medieval, unforgettable, original, fun, with children, civil, simple, on a sidecar or on horseback, with a marquee, heartfelt, autumnal or warm, intimate… however you want it, however you feel it. If you have a rough idea of how you want your wedding to be and you follow it through, it will be an unforgettable day. Come and tell us about it! We'll bring all the care and dedication you deserve.",
         "Okalarre's carefully crafted catering service, provided by renowned caterers, embraces every style: traditional, innovative, with contrasts… to achieve a personalised and meticulous result.",
         "Come and enjoy your wedding in a place that is unique and exclusively yours, with no time limit."],
       },
},

"comuniones": {
 "es":{"seo_t":"Comuniones en Navarra — Finca Okalarre | Comuniones en plena naturaleza",
       "seo_d":"La comunión de tus hijos en plena naturaleza, con amplia terraza y jardín. Fotos espectaculares y menús pensados para pequeños y grandes.",
       "eyebrow":"Celebraciones","title":"Comuniones",
       "sub":"La comunión de tus hijos en plena naturaleza, en Okalarre.",
       "body":[
         "El día de la comunión es un día muy especial para nuestros hijos. Pero también es un día de muchos nervios, por eso celebrarla con nosotros, en Okalarre, tiene la ventaja de que pueden disfrutar de la naturaleza y jugar en nuestra amplia terraza o en el jardín, descargando así las tensiones acumuladas durante todo el día.",
         "Además te garantizamos que las fotos de ese día tan especial serán realmente espectaculares gracias al entorno donde nos encontramos.",
         "Nos adaptamos a todo tipo de celebraciones, más íntimas o en familia pero también podemos acoger a todos los invitados que se quieran. Las comuniones son todas especiales, pequeñas o grandes, casuales o elegantes.",
         "Respecto al menú, lo mejor es pensar en pequeños y grandes para que así disfruten todos. Ponte en contacto con nosotros y juntos pensaremos en el día más bonito de tu hijo o hija."],
       },
 "eu":{"seo_t":"Jaunartzeak Nafarroan — Finca Okalarre | Jaunartzeak naturan",
       "seo_d":"Zure seme-alaben jaunartzea naturan, terraza eta lorategi zabalarekin. Argazki ikusgarriak eta txiki zein handientzako menuak.",
       "eyebrow":"Ospakizunak","title":"Jaunartzeak",
       "sub":"Zure seme-alaben jaunartzea naturan, Okalarren.",
       "body":[
         "Jaunartze eguna oso berezia da gure seme-alabentzat. Baina urduritasun handiko eguna ere bada, eta horregatik, gurean, Okalarren ospatzeak naturaz gozatzeko eta gure terraza edo lorategi handian jolasteko abantaila ematen die, eguneko tentsio guztiak bertan ahaztu ahal izateko.",
         "Gainera, egun berezi horretako argazkiak benetan ikusgarriak izango direla bermatzen dizugu, gauden ingurunari esker.",
         "Era guztietako ospakizunetara egokitzen gara, intimoagoetara edo familiakoetara, baina nahi diren gonbidatu guztiak ere har ditzakegu. Jaunartze guztiak dira bereziak, txikiak zein handiak, lasaiak zein dotoreak.",
         "Menuari dagokionez, onena txikiak zein handiak kontuan hartzea da, denek goza dezaten. Jar zaitez gurekin harremanetan eta elkarrekin pentsatuko dugu zure seme edo alabaren egunik politena."],
       },
 "fr":{"seo_t":"Communions en Navarre — Finca Okalarre | Communions en pleine nature",
       "seo_d":"La communion de vos enfants en pleine nature, avec grande terrasse et jardin. Des photos spectaculaires et des menus pensés pour petits et grands.",
       "eyebrow":"Célébrations","title":"Communions",
       "sub":"La communion de vos enfants en pleine nature, à Okalarre.",
       "body":[
         "Le jour de la communion est un jour très spécial pour nos enfants. Mais c'est aussi un jour de grande émotion, c'est pourquoi la célébrer chez nous, à Okalarre, présente l'avantage qu'ils peuvent profiter de la nature et jouer sur notre grande terrasse ou dans le jardin, évacuant ainsi les tensions accumulées tout au long de la journée.",
         "De plus, nous vous garantissons que les photos de cette journée si spéciale seront vraiment spectaculaires grâce au cadre dans lequel nous nous trouvons.",
         "Nous nous adaptons à tout type de célébrations, plus intimes ou en famille, mais nous pouvons aussi accueillir tous les invités que vous souhaitez. Les communions sont toutes spéciales, petites ou grandes, décontractées ou élégantes.",
         "Concernant le menu, le mieux est de penser aux petits comme aux grands pour que tous en profitent. Contactez-nous et nous penserons ensemble au plus beau jour de votre enfant."],
       },
 "en":{"seo_t":"Communions in Navarre — Finca Okalarre | Communions in pure nature",
       "seo_d":"Your children's communion in pure nature, with a large terrace and garden. Spectacular photos and menus designed for young and old alike.",
       "eyebrow":"Celebrations","title":"Communions",
       "sub":"Your children's communion in pure nature, at Okalarre.",
       "body":[
         "Communion day is a very special day for our children. But it's also a day of much excitement, which is why celebrating it with us, at Okalarre, has the advantage that they can enjoy nature and play on our large terrace or in the garden, releasing the tension built up throughout the day.",
         "We also guarantee that the photos of that special day will be truly spectacular thanks to the setting we are in.",
         "We adapt to all kinds of celebrations, more intimate or family ones, but we can also host as many guests as you wish. Communions are all special, big or small, casual or elegant.",
         "As for the menu, it's best to think of both young and old so that everyone enjoys it. Get in touch with us and together we'll plan the most beautiful day for your son or daughter."],
       },
},

"eventos": {
 "es":{"seo_t":"Fiestas privadas y eventos — Finca Okalarre | Espacio multifuncional, Bera-Bidasoa",
       "seo_d":"Celebra con tus amigos o tu familia una fiesta privada en Okalarre. Un espacio multifuncional con posibilidades infinitas y privacidad total.",
       "eyebrow":"Celebraciones","title":"Fiestas privadas y eventos",
       "sub":"No solo de bodas viven los amigos… celebra con ellos en un lugar tan especial.",
       "body":[
         "No solo de bodas viven los amigos… Hay muchos motivos para juntarse con ellos o con la familia, todas las excusas son buenas cuando se busca pasar un buen rato. Por eso, disponer de un lugar tan especial es un lujo y te garantizamos que sea cual sea el motivo de la celebración va a ser perfecta.",
         "Ponemos a tu disposición un espacio multifuncional donde puedes organizar lo que quieras y como quieras. Las posibilidades son infinitas y la privacidad total.",
         "Las posibilidades son infinitas y la privacidad total para la celebración de cualquier tipo de evento."],
       },
 "eu":{"seo_t":"Festa pribatuak eta ekitaldiak — Finca Okalarre | Espazio funtzioanitza",
       "seo_d":"Ospatu lagunekin edo familiarekin festa pribatu bat Okalarren. Espazio funtzioanitza, aukera mugagabeak eta erabateko pribatutasuna.",
       "eyebrow":"Ospakizunak","title":"Festa pribatuak eta ekitaldiak",
       "sub":"Lagunak ez dira ezkontzaz soilik bizi… ospatu haiekin leku berezi batean.",
       "body":[
         "Lagunak ez dira ezkontzaz soilik bizi… Haiekin edo familiarekin elkartzeko arrazoi asko daude, aitzakia guztiak dira onak une on bat pasatu nahi denean. Horregatik, hain leku berezia izatea luxua da, eta bermatzen dizugu, ospakizunaren arrazoia edozein dela ere, paregabea izango dela.",
         "Espazio funtzioanitza jartzen dugu zure esku, nahi duzun hori nahi duzun bezala antolatu ahal izateko. Aukerak mugagabeak dira eta pribatutasuna erabatekoa.",
         "Aukerak mugagabeak dira eta pribatutasuna erabatekoa edozein ekitaldi mota ospatzeko."],
       },
 "fr":{"seo_t":"Fêtes privées et événements — Finca Okalarre | Espace polyvalent, Bera-Bidassoa",
       "seo_d":"Célébrez avec vos amis ou votre famille une fête privée à Okalarre. Un espace polyvalent aux possibilités infinies et une intimité totale.",
       "eyebrow":"Célébrations","title":"Fêtes privées et événements",
       "sub":"Les amis ne vivent pas que de mariages… célébrez avec eux dans un lieu si spécial.",
       "body":[
         "Les amis ne vivent pas que de mariages… Il y a beaucoup de raisons de se réunir avec eux ou en famille, tous les prétextes sont bons quand on cherche à passer un bon moment. C'est pourquoi disposer d'un lieu si spécial est un luxe, et nous vous garantissons que, quelle que soit la raison de la célébration, elle sera parfaite.",
         "Nous mettons à votre disposition un espace polyvalent où vous pouvez organiser ce que vous voulez et comme vous le voulez. Les possibilités sont infinies et l'intimité totale.",
         "Les possibilités sont infinies et l'intimité totale pour la célébration de tout type d'événement."],
       },
 "en":{"seo_t":"Private parties & events — Finca Okalarre | Multipurpose space, Bera-Bidasoa",
       "seo_d":"Celebrate a private party with friends or family at Okalarre. A multipurpose space with infinite possibilities and total privacy.",
       "eyebrow":"Celebrations","title":"Private parties and events",
       "sub":"Friends don't live by weddings alone… celebrate with them in such a special place.",
       "body":[
         "Friends don't live by weddings alone… There are many reasons to get together with them or with family — every excuse is a good one when you're looking to have a great time. That's why having such a special place is a luxury, and we guarantee that whatever the reason for the celebration, it will be perfect.",
         "We put a multipurpose space at your disposal where you can organise whatever you want, however you want. The possibilities are infinite and the privacy total.",
         "The possibilities are infinite and the privacy total for celebrating any kind of event."],
       },
},

"empresa": {
 "es":{"seo_t":"Reuniones de empresa y eventos corporativos — Finca Okalarre, Navarra",
       "seo_d":"Reuniones de empresa en un lugar tranquilo en plena naturaleza. Infraestructura para presentaciones, coaching y team building, con un buen menú.",
       "eyebrow":"Celebraciones","title":"Reuniones de empresa",
       "sub":"Un equipo motivado y valorado mejora su rendimiento. Reúnelo en plena naturaleza.",
       "body":[
         "Hace tiempo que los empleadores o empresarios descubrieron que las actividades outdoor en grupo fuera del ámbito laboral y en un ambiente distendido, mejora las relaciones laborales de los empleados porque potencian su comunicación y desarrollan habilidades que en otro contexto pasarían desapercibidas. Es decir, un equipo motivado y valorado mejora su rendimiento laboral.",
         "El evento no tiene que durar todo el día y en Okalarre te garantizamos el éxito de tu convocatoria, ya que cualquier reunión entorno a un buen menú, siempre es bien recibida. Además podemos ofrecerte toda la infraestructura que necesites para presentaciones, sesiones de coaching, charlas de motivación y/o liderazgo, inteligencia emocional en el trabajo, etc.",
         "Como empresario es muy positivo organizar una actividad para conocer al grupo de asistentes y sus impresiones sobre su trabajo o comunicar a los empleados nuevos los retos de la empresa. También sirve para mejorar la comunicación entre departamentos, y es que incluso en las PYMES, la única relación que tienen algunas personas entre sí es a través del teléfono o del e-mail.",
         "Otros motivos pueden ser premiar a los empleados por la consecución de unos objetivos o que incluso se involucren más con el proyecto. Lo que se pretende en muchos casos es «fidelizar» al empleado para que se sienta a gusto y entienda que es una pieza importante en la estructura.",
         "Y por último siempre se estrechan los lazos con otros departamentos de la empresa. En resumen, siempre hay una buena excusa para reunirse o agradecer a tus empleados su compromiso con la empresa en un lugar único como es Okalarre."],
       },
 "eu":{"seo_t":"Enpresa bilerak eta ekitaldi korporatiboak — Finca Okalarre, Nafarroa",
       "seo_d":"Enpresa bilerak leku lasai batean, naturaren erdian. Azpiegitura aurkezpenetarako, coaching-erako eta talde-lanerako, menu on batekin.",
       "eyebrow":"Ospakizunak","title":"Enpresa bilerak",
       "sub":"Talde motibatu eta baloratuak hobeto errenditzen du. Elkartu ezazu naturan.",
       "body":[
         "Aspaldi konturatu ziren enplegatzaileak edo enpresariak lan-eremutik kanpoko taldeko kanpo-jarduerek, giro lasai batean, langileen lan-harremanak hobetzen dituztela, beren komunikazioa indartzen baitute eta beste testuinguru batean oharkabean igaroko liratekeen gaitasunak garatzen baitituzte. Hau da, talde motibatu eta baloratu batek bere lan-errendimendua hobetzen du.",
         "Ekitaldiak ez du egun osoa iraun behar eta Okalarren zure deialdiaren arrakasta bermatzen dizugu, izan ere, menu on baten inguruko edozein bilera beti ongi etorria da. Gainera, aurkezpenetarako, coaching saioetarako, motibazio eta/edo lidergo hitzaldietarako eta laneko adimen emozionalerako behar duzun azpiegitura guztia eskain diezazukegu.",
         "Enpresari gisa oso positiboa da jarduera bat antolatzea bertaratutako taldea eta beren lanari buruzko inpresioak ezagutzeko, edo langile berriei enpresaren erronkak jakinarazteko. Sailen arteko komunikazioa hobetzeko ere balio du.",
         "Beste arrazoi batzuk izan daitezke langileak helburu batzuk lortzeagatik saritzea edo proiektuan gehiago inplikatzea. Kasu askotan langilea «fidelizatzea» da helburua, eroso senti dadin eta egituran pieza garrantzitsua dela uler dezan.",
         "Eta azkenik, beti estutzen dira loturak enpresako beste sailekin. Laburbilduz, beti dago aitzakia ona elkartzeko edo langileei enpresarekiko konpromisoa eskertzeko Okalarre bezalako leku paregabe batean."],
       },
 "fr":{"seo_t":"Réunions d'entreprise et événements corporatifs — Finca Okalarre, Navarre",
       "seo_d":"Réunions d'entreprise dans un lieu calme en pleine nature. Infrastructure pour présentations, coaching et team building, autour d'un bon menu.",
       "eyebrow":"Célébrations","title":"Réunions d'entreprise",
       "sub":"Une équipe motivée et valorisée améliore ses performances. Réunissez-la en pleine nature.",
       "body":[
         "Il y a longtemps que les employeurs ou les chefs d'entreprise ont découvert que les activités de groupe en plein air, en dehors du cadre professionnel et dans une ambiance détendue, améliorent les relations de travail des employés, car elles renforcent leur communication et développent des compétences qui passeraient inaperçues dans un autre contexte. Autrement dit, une équipe motivée et valorisée améliore ses performances professionnelles.",
         "L'événement ne doit pas durer toute la journée et à Okalarre nous vous garantissons le succès de votre rencontre, car toute réunion autour d'un bon menu est toujours bien accueillie. De plus, nous pouvons vous offrir toute l'infrastructure dont vous avez besoin pour des présentations, des séances de coaching, des conférences de motivation et/ou de leadership, l'intelligence émotionnelle au travail, etc.",
         "En tant que chef d'entreprise, il est très positif d'organiser une activité pour connaître le groupe de participants et leurs impressions sur leur travail, ou pour communiquer aux nouveaux employés les défis de l'entreprise. Cela sert aussi à améliorer la communication entre les services.",
         "D'autres motifs peuvent être de récompenser les employés pour l'atteinte d'objectifs ou de les impliquer davantage dans le projet. Ce que l'on cherche souvent, c'est à « fidéliser » l'employé pour qu'il se sente à l'aise et comprenne qu'il est une pièce importante de la structure.",
         "Et enfin, on resserre toujours les liens avec d'autres services de l'entreprise. En résumé, il y a toujours une bonne excuse pour se réunir ou remercier vos employés de leur engagement dans un lieu unique comme Okalarre."],
       },
 "en":{"seo_t":"Corporate meetings & events — Finca Okalarre, Navarre",
       "seo_d":"Corporate meetings in a peaceful place in pure nature. Infrastructure for presentations, coaching and team building, around a great menu.",
       "eyebrow":"Celebrations","title":"Corporate events",
       "sub":"A motivated, valued team performs better. Bring it together in pure nature.",
       "body":[
         "Employers and business owners discovered long ago that outdoor group activities outside the workplace, in a relaxed atmosphere, improve employees' working relationships because they boost communication and develop skills that would otherwise go unnoticed. In other words, a motivated and valued team improves its performance.",
         "The event doesn't have to last all day, and at Okalarre we guarantee the success of your gathering, since any meeting around a good menu is always well received. We can also offer all the infrastructure you need for presentations, coaching sessions, motivation and/or leadership talks, emotional intelligence at work, and more.",
         "As a business owner, it's very positive to organise an activity to get to know the group of attendees and their impressions about their work, or to communicate the company's challenges to new employees. It also helps improve communication between departments.",
         "Other reasons may be to reward employees for achieving certain goals or to get them more involved in the project. In many cases the aim is to build employee loyalty so they feel comfortable and understand that they are an important part of the structure.",
         "And finally, bonds with other departments are always strengthened. In short, there's always a good excuse to get together or thank your employees for their commitment in a unique place like Okalarre."],
       },
},

"espacios": {
 "es":{"seo_t":"Espacios — Finca Okalarre | Comedor 150 pax y terrazas con vistas al valle",
       "seo_d":"Espacio interior para 150 invitados con grandes ventanales y vistas al valle Baztan-Bidasoa, terraza-jardín con haima, chill-out y terraza de bienvenida con vistas al Larun.",
       "eyebrow":"El espacio","title":"Comedor y terrazas en plena naturaleza",
       "sub":"Interior y exterior que podéis personalizar a vuestro gusto para que vuestro día sea diferente e inolvidable.",
       "body":[
         "Disponemos de un ESPACIO INTERIOR con capacidad para 150 invitados, con grandes ventanales y vistas al valle Baztan-Bidasoa.",
         "ESPACIOS EXTERIORES con amplias zonas verdes: terraza-jardín sur, donde se levanta una preciosa haima y donde podréis disfrutar del cóctel, la ceremonia y/o el baile sin límite de horario; terraza-jardín con orientación oeste y su espacio chill-out; además de la terraza de bienvenida en la fachada principal con vistas al Larun.",
         "Espacios interior y exterior que podéis personalizar a vuestro gusto para que vuestro día sea diferente e inolvidable."],
       },
 "eu":{"seo_t":"Espazioak — Finca Okalarre | 150 pertsonentzako jantokia eta terrazak",
       "seo_d":"150 pertsonentzako barne-espazioa leiho handiekin eta Baztan-Bidasoa haranerako bistekin, haima duen lorategi-terraza, chill-out eta Larunera begira dagoen ongietorri-terraza.",
       "eyebrow":"Espazioa","title":"Jantokia eta terrazak naturan",
       "sub":"Barnealdea eta kanpoaldea zuen gustura pertsonalizatu ditzakezue zuen eguna desberdina eta ahaztezina izan dadin.",
       "body":[
         "Bidasoak bustitako lurren ikuspegi zoragarria eskaintzen duen 150 pertsonentzako BARNE-ESPAZIOA daukagu, leiho handiekin eta Baztan-Bidasoa haranera begira.",
         "KANPO-ESPAZIOAK zona berde zabalekin: hegoaldeko lorategi-terraza, non haima eder bat altxatzen den eta non koktelaz, zeremoniaz eta/edo dantzaz goza dezakezuen ordutegi mugarik gabe; mendebaldera begira dagoen lorategi-terraza eta bere chill-out espazioa; eta fatxada nagusiko ongietorri-terraza, Larunera begira.",
         "Barne eta kanpo espazioak, zuen gustura pertsonalizatzeko, zuen eguna desberdina eta ahaztezina izan dadin."],
       },
 "fr":{"seo_t":"Espaces — Finca Okalarre | Salle 150 pers. et terrasses avec vue sur la vallée",
       "seo_d":"Espace intérieur pour 150 invités avec de grandes baies vitrées et vue sur la vallée du Baztan-Bidassoa, terrasse-jardin avec chapiteau, chill-out et terrasse d'accueil avec vue sur le Larun.",
       "eyebrow":"L'espace","title":"Salle et terrasses en pleine nature",
       "sub":"Intérieur et extérieur que vous pouvez personnaliser à votre guise pour que votre journée soit différente et inoubliable.",
       "body":[
         "Nous disposons d'un ESPACE INTÉRIEUR pouvant accueillir 150 invités, avec de grandes baies vitrées et une vue privilégiée sur la vallée du Baztan-Bidassoa.",
         "DES ESPACES EXTÉRIEURS avec de vastes zones vertes : terrasse-jardin sud, où se dresse un magnifique chapiteau et où vous pourrez profiter du cocktail, de la cérémonie et/ou de la danse sans limite d'horaire ; terrasse-jardin orientée ouest et son espace chill-out ; ainsi que la terrasse d'accueil sur la façade principale avec vue sur le Larun.",
         "Des espaces intérieurs et extérieurs que vous pouvez personnaliser à votre guise pour que votre journée soit différente et inoubliable."],
       },
 "en":{"seo_t":"Spaces — Finca Okalarre | 150-guest hall and terraces with valley views",
       "seo_d":"Indoor space for 150 guests with large windows and views of the Baztan-Bidasoa valley, a garden terrace with marquee, chill-out area and a welcome terrace overlooking the Larun.",
       "eyebrow":"The space","title":"Hall and terraces in pure nature",
       "sub":"Indoor and outdoor spaces you can personalise to your taste so your day is different and unforgettable.",
       "body":[
         "We have an INDOOR SPACE with capacity for 150 guests, with large windows and views over the Baztan-Bidasoa valley.",
         "OUTDOOR SPACES with broad green areas: a south garden terrace, where a beautiful marquee rises and where you can enjoy the cocktail, the ceremony and/or dancing with no time limit; a west-facing garden terrace with its chill-out area; plus the welcome terrace on the main façade overlooking the Larun.",
         "Indoor and outdoor spaces you can personalise to your taste so your day is different and unforgettable."],
       },
},

"gastronomia": {
 "es":{"seo_t":"Gastronomía — Mahercatering en Finca Okalarre | Catering propio premiado",
       "seo_d":"Una de las propuestas gastronómicas más creativas y de vanguardia: Mahercatering. Más de 30 años de experiencia y premios como Madrid Fusión o Wedding Awards.",
       "eyebrow":"Gastronomía","title":"Experience & Food — Mahercatering",
       "sub":"Una propuesta que conjuga creatividad, calidad y sabores tradicionales, junto a los nuevos sabores del mundo.",
       "body":[
         "Descubre una de las propuestas gastronómicas más creativas y de vanguardia: Mahercatering. Una propuesta que conjuga creatividad, calidad y sabores tradicionales, junto a los nuevos sabores del mundo.",
         "Con más de 30 años de experiencia, a lo largo de su trayectoria ha sido reconocida con multitud de premios entre los que destacan el Premio «Uno de los 10 mejores platos de la década» (Madrid Fusión), el Premio Marqués de Desío (Academia Española de Gastronomía), el Premio de Turismo a la Innovación (Gobierno de Navarra), el Vogue Catering Selección y el Wedding Awards 2017 de Bodas.net.",
         "EXPERIENCE & FOOD. Mahercatering convierte cualquier evento en una experiencia gastronómica y visual única e inolvidable, con capacidad y versatilidad para adaptarse a cualquier espacio o singularidad de un evento."],
       },
 "eu":{"seo_t":"Gastronomia — Mahercatering Finca Okalarren | Catering propio saritua",
       "seo_d":"Proposamen gastronomiko sortzaileenetako eta abangoardistenetako bat: Mahercatering. 30 urtetik gorako esperientzia eta Madrid Fusión edo Wedding Awards bezalako sariak.",
       "eyebrow":"Gastronomia","title":"Experience & Food — Mahercatering",
       "sub":"Sormena, kalitatea eta zapore tradizionalak munduko zapore berriekin uztartzen dituen proposamena.",
       "body":[
         "Ezagutu proposamen gastronomiko sortzaileenetako eta abangoardistenetako bat: Mahercatering. Sormena, kalitatea eta zapore tradizionalak munduko zapore berriekin uztartzen dituen proposamena.",
         "30 urtetik gorako esperientziarekin, bere ibilbidean zehar sari ugarirekin saritua izan da, besteak beste: «Hamarkadako 10 plater onenetako bat» Saria (Madrid Fusión), Marqués de Desío Saria (Espainiako Gastronomia Akademia), Berrikuntzarako Turismo Saria (Nafarroako Gobernua), Vogue Catering Selección eta Bodas.net-en 2017ko Wedding Awards.",
         "EXPERIENCE & FOOD. Mahercateringek edozein ekitaldi esperientzia gastronomiko eta bisual paregabe eta ahaztezin bihurtzen du, edozein espaziotara edo ekitaldiren berezitasunera egokitzeko gaitasun eta malgutasunarekin."],
       },
 "fr":{"seo_t":"Gastronomie — Mahercatering à Finca Okalarre | Traiteur maison primé",
       "seo_d":"L'une des propositions gastronomiques les plus créatives et avant-gardistes : Mahercatering. Plus de 30 ans d'expérience et des prix comme Madrid Fusión ou les Wedding Awards.",
       "eyebrow":"Gastronomie","title":"Experience & Food — Mahercatering",
       "sub":"Une proposition qui allie créativité, qualité et saveurs traditionnelles, aux nouvelles saveurs du monde.",
       "body":[
         "Découvrez l'une des propositions gastronomiques les plus créatives et avant-gardistes : Mahercatering. Une proposition qui allie créativité, qualité et saveurs traditionnelles, aux nouvelles saveurs du monde.",
         "Avec plus de 30 ans d'expérience, elle a été récompensée tout au long de son parcours par de nombreux prix, parmi lesquels le Prix « L'un des 10 meilleurs plats de la décennie » (Madrid Fusión), le Prix Marqués de Desío (Académie Espagnole de Gastronomie), le Prix du Tourisme à l'Innovation (Gouvernement de Navarre), le Vogue Catering Selección et les Wedding Awards 2017 de Bodas.net.",
         "EXPERIENCE & FOOD. Mahercatering transforme tout événement en une expérience gastronomique et visuelle unique et inoubliable, avec la capacité et la polyvalence de s'adapter à tout espace ou à la singularité d'un événement."],
       },
 "en":{"seo_t":"Gastronomy — Mahercatering at Finca Okalarre | Award-winning in-house catering",
       "seo_d":"One of the most creative and avant-garde culinary proposals: Mahercatering. Over 30 years of experience and awards such as Madrid Fusión and the Wedding Awards.",
       "eyebrow":"Gastronomy","title":"Experience & Food — Mahercatering",
       "sub":"A proposal that blends creativity, quality and traditional flavours with new flavours from around the world.",
       "body":[
         "Discover one of the most creative and avant-garde culinary proposals: Mahercatering. A proposal that blends creativity, quality and traditional flavours with new flavours from around the world.",
         "With over 30 years of experience, throughout its career it has earned numerous awards, among which stand out the “One of the 10 best dishes of the decade” Award (Madrid Fusión), the Marqués de Desío Award (Spanish Academy of Gastronomy), the Tourism Innovation Award (Government of Navarre), the Vogue Catering Selección and the 2017 Wedding Awards by Bodas.net.",
         "EXPERIENCE & FOOD. Mahercatering turns any event into a unique and unforgettable gastronomic and visual experience, with the capacity and versatility to adapt to any space or the singularity of an event."],
       },
},

"localizacion": {
 "es":{"seo_t":"Localización — Finca Okalarre | Cómo llegar, entre Bera, Gipuzkoa y Francia",
       "seo_d":"La finca se encuentra en Bera de Bidasoa, a 15 min de Irun, 30 de San Sebastián y 45 de Pamplona. Coordenadas GPS y cómo llegar desde Bera o Iparralde.",
       "eyebrow":"Cómo llegar","title":"Entre Bera e Ibardin, entre Gipuzkoa, Navarra y Francia",
       "sub":"A 15 minutos de Irun, 30 de San Sebastián y 45 de Pamplona.",
       "body":[
         "La finca se encuentra ubicada en Bera de Bidasoa, a tan solo 15 minutos de Irun, 30 minutos de San Sebastián y 45 minutos de Pamplona.",
         "Okalarre está situada en una desviación a escasos metros de llegar a Ibardin desde Bera. Por un cómodo camino asfaltado de 1 km nos adentramos en una frondosa vegetación y enseguida se llega a una atalaya sobre la que está construido Okalarre.",
         "En las tierras del Bidasoa, disfrutamos de la montaña de la Costa Vasca: Ibardin, cerca de la costa labortana, en Bera (Navarra). El Barrio de Ibardin está situado en un alto a 350 m de altura sobre el nivel del mar. El acceso por carretera se puede realizar bien por la parte navarra, subiendo desde Bera un pequeño puerto de unos 5 km, o bien por la parte de Iparralde (País Vasco Francés), subiendo desde Urruña un pequeño puerto de unos 6,5 km."],
       },
 "eu":{"seo_t":"Kokapena — Finca Okalarre | Nola iritsi, Bera, Gipuzkoa eta Frantzia artean",
       "seo_d":"Finca Bera de Bidasoan dago, Irundik 15 minutura, Donostiatik 30era eta Iruñetik 45era. GPS koordenatuak eta nola iritsi Beratik edo Iparraldetik.",
       "eyebrow":"Nola iritsi","title":"Bera eta Ibardin artean, Gipuzkoa, Nafarroa eta Frantzia artean",
       "sub":"Irundik 15 minutura, Donostiatik 30era eta Iruñetik 45era.",
       "body":[
         "Finca Bera de Bidasoan dago kokatuta, Irundik 15 minutura besterik ez, Donostiatik 30 minutura eta Iruñetik 45 minutura.",
         "Okalarre Beratik Ibardinera iristear dagoen desbideratze batean dago. Kilometro 1eko bide asfaltatu eroso batetik landaretza oparo batean barneratzen gara eta berehala iristen gara Okalarre eraikita dagoen begiratoki batera.",
         "Bidasoako lurretan, Euskal Kostaldeko mendiaz gozatzen dugu: Ibardin, Lapurdiko kostaldetik gertu, Beran (Nafarroa). Ibardin auzoa itsas mailatik 350 m-ko altueran dago. Errepidez sar daiteke, bai Nafarroako aldetik, Beratik 5 km inguruko portu txiki bat igoz, bai Iparraldetik, Urruñatik 6,5 km inguruko portu txiki bat igoz."],
       },
 "fr":{"seo_t":"Localisation — Finca Okalarre | Comment venir, entre Bera, Gipuzkoa et France",
       "seo_d":"Le domaine se trouve à Bera de Bidassoa, à 15 min d'Irun, 30 de Saint-Sébastien et 45 de Pampelune. Coordonnées GPS et accès depuis Bera ou Iparralde.",
       "eyebrow":"Comment venir","title":"Entre Bera et Ibardin, entre Gipuzkoa, Navarre et France",
       "sub":"À 15 minutes d'Irun, 30 de Saint-Sébastien et 45 de Pampelune.",
       "body":[
         "Le domaine est situé à Bera de Bidassoa, à seulement 15 minutes d'Irun, 30 minutes de Saint-Sébastien et 45 minutes de Pampelune.",
         "Okalarre se situe sur une déviation, à quelques mètres avant d'arriver à Ibardin depuis Bera. Par un chemin goudronné confortable d'1 km, nous pénétrons dans une végétation luxuriante et l'on arrive aussitôt à un belvédère sur lequel est construit Okalarre.",
         "Sur les terres de la Bidassoa, nous profitons de la montagne de la Côte Basque : Ibardin, près de la côte du Labourd, à Bera (Navarre). Le quartier d'Ibardin est situé sur une hauteur à 350 m d'altitude. L'accès par la route peut se faire soit par le côté navarrais, en montant depuis Bera un petit col d'environ 5 km, soit par le côté d'Iparralde (Pays Basque français), en montant depuis Urrugne un petit col d'environ 6,5 km."],
       },
 "en":{"seo_t":"Location — Finca Okalarre | How to get here, between Bera, Gipuzkoa & France",
       "seo_d":"The estate is in Bera de Bidasoa, 15 min from Irun, 30 from San Sebastián and 45 from Pamplona. GPS coordinates and directions from Bera or Iparralde.",
       "eyebrow":"How to get here","title":"Between Bera and Ibardin, where Gipuzkoa, Navarre and France meet",
       "sub":"15 minutes from Irun, 30 from San Sebastián and 45 from Pamplona.",
       "body":[
         "The estate is located in Bera de Bidasoa, just 15 minutes from Irun, 30 minutes from San Sebastián and 45 minutes from Pamplona.",
         "Okalarre is set on a turn-off, a few metres before reaching Ibardin from Bera. Along a comfortable 1 km paved road we head into lush vegetation and soon reach a vantage point on which Okalarre is built.",
         "On the lands of the Bidasoa, we enjoy the mountains of the Basque Coast: Ibardin, near the Labourd coast, in Bera (Navarre). The Ibardin district sits on a height 350 m above sea level. It can be reached by road either from the Navarre side, climbing a small pass of about 5 km from Bera, or from the Iparralde side (French Basque Country), climbing a small pass of about 6.5 km from Urrugne."],
       },
},
}

# FAQ items (preguntas frecuentes) — original Q/A
FAQ = {
 "es":[("¿Celebráis más de un evento al día?","No. En Okalarre solo se celebra un evento al día: el día es enteramente vuestro."),
       ("¿Cuántos invitados puedo tener?","Hasta 150 invitados."),
       ("¿Es posible alquilar únicamente el espacio, sin el servicio de catering?","No, el espacio se ofrece siempre con nuestro servicio de catering."),
       ("¿Disponéis de catering y cocina propia?","Sí, ambos."),
       ("¿Es posible adaptar o modificar los menús?","Sí, adaptamos los menús a vuestro gusto."),
       ("¿Disponéis de menús especiales?","Sí: vegetarianos, veganos, diabéticos, hipertensos, celíacos…"),
       ("¿Servís también la tarta de boda?","Sí."),
       ("¿Hay límite de hora en las celebraciones?","No. Sin límite de horario."),
       ("¿Exclusividad de fotógrafo?","No, podéis traer vuestro propio fotógrafo."),
       ("¿Exclusividad de música?","No, podéis traer vuestra propia música."),
       ("¿Exclusividad de catering?","No."),
       ("¿Existe algún pago fijo por el lugar?","Sí, existe un pago fijo por el espacio."),
       ("¿Hay recargo si no se llega al mínimo de invitados?","No, no hay ningún recargo."),
       ("¿Cómo se efectúa el pago?","Según acuerdo entre ambas partes.")],
 "eu":[("Egunean ekitaldi bat baino gehiago ospatzen duzue?","Ez. Okalarren egunean ekitaldi bakarra ospatzen da: eguna zuena da osorik."),
       ("Zenbat gonbidatu izan ditzaket?","150 gonbidatu arte."),
       ("Espazioa soilik aloka daiteke, catering zerbitzurik gabe?","Ez, espazioa beti gure catering zerbitzuarekin eskaintzen da."),
       ("Catering eta sukalde propioa duzue?","Bai, biak."),
       ("Menuak egokitu edo aldatu daitezke?","Bai, menuak zuen gustura egokitzen ditugu."),
       ("Menu bereziak dituzue?","Bai: begetarianoak, beganoak, diabetikoak, hipertentsoak, zeliakoak…"),
       ("Ezkontza-tarta ere zerbitzatzen duzue?","Bai."),
       ("Ordu-mugarik dago ospakizunetan?","Ez. Ordutegi mugarik gabe."),
       ("Argazkilari esklusibotasunik?","Ez, zeuen argazkilaria ekar dezakezue."),
       ("Musika esklusibotasunik?","Ez, zeuen musika ekar dezakezue."),
       ("Catering esklusibotasunik?","Ez."),
       ("Lekuagatik ordainketa finkorik ba al dago?","Bai, espazioagatik ordainketa finko bat dago."),
       ("Errekargurik ba al dago gonbidatu-gutxienekora iritsi ezean?","Ez, ez dago inolako errekargurik."),
       ("Nola egiten da ordainketa?","Bi aldeen arteko akordioaren arabera.")],
 "fr":[("Célébrez-vous plus d'un événement par jour ?","Non. À Okalarre, un seul événement est célébré par jour : la journée est entièrement à vous."),
       ("Combien d'invités puis-je avoir ?","Jusqu'à 150 invités."),
       ("Est-il possible de louer uniquement l'espace, sans le service de traiteur ?","Non, l'espace est toujours proposé avec notre service de traiteur."),
       ("Disposez-vous d'un traiteur et d'une cuisine propres ?","Oui, les deux."),
       ("Est-il possible d'adapter ou de modifier les menus ?","Oui, nous adaptons les menus à votre goût."),
       ("Disposez-vous de menus spéciaux ?","Oui : végétariens, végétaliens, diabétiques, hypertendus, cœliaques…"),
       ("Servez-vous aussi le gâteau de mariage ?","Oui."),
       ("Y a-t-il une limite d'horaire pour les célébrations ?","Non. Sans limite d'horaire."),
       ("Exclusivité du photographe ?","Non, vous pouvez amener votre propre photographe."),
       ("Exclusivité de la musique ?","Non, vous pouvez amener votre propre musique."),
       ("Exclusivité du traiteur ?","Non."),
       ("Existe-t-il un paiement fixe pour le lieu ?","Oui, il existe un paiement fixe pour l'espace."),
       ("Y a-t-il un supplément si le minimum d'invités n'est pas atteint ?","Non, aucun supplément."),
       ("Comment s'effectue le paiement ?","Selon accord entre les deux parties.")],
 "en":[("Do you host more than one event per day?","No. At Okalarre only one event is held per day: the day is entirely yours."),
       ("How many guests can I have?","Up to 150 guests."),
       ("Is it possible to rent only the venue, without the catering service?","No, the venue always comes with our catering service."),
       ("Do you have your own catering and kitchen?","Yes, both."),
       ("Is it possible to adapt or modify the menus?","Yes, we adapt the menus to your taste."),
       ("Do you offer special menus?","Yes: vegetarian, vegan, diabetic, low-sodium, coeliac…"),
       ("Do you also serve the wedding cake?","Yes."),
       ("Is there a time limit on celebrations?","No. No time limit."),
       ("Photographer exclusivity?","No, you can bring your own photographer."),
       ("Music exclusivity?","No, you can bring your own music."),
       ("Catering exclusivity?","No."),
       ("Is there a fixed fee for the venue?","Yes, there is a fixed fee for the space."),
       ("Is there a surcharge if the guest minimum isn't reached?","No, there is no surcharge."),
       ("How is payment made?","As agreed between both parties.")],
}

# Home hero + intro
HOME = {
 "es":{"seo_t":"Bodas en Navarra — Finca Okalarre | Bodas y eventos en plena naturaleza",
       "seo_d":"Bodas y eventos en plena naturaleza, en el valle del Baztan-Bidasoa. Privacidad total, exteriores de ensueño y celebración sin límite de horario. A 15 min de Irun.",
       "hero_t":"Bodas y eventos en plena naturaleza",
       "hero_sub":"Un excepcional enclave natural en las alturas del valle encantado del Baztan-Bidasoa. Privacidad total, exteriores de ensueño y una celebración sin límite de horario.",
       "anchor":"¿Cuántas cosas excepcionales suceden a las personas que queremos y que merezcan celebrarse? Muchísimas… Estamos seguros de que Okalarre es el lugar perfecto para celebrar, por lo menos uno, de esos acontecimientos tan especiales.",
       "intro":"Un excepcional enclave natural en las alturas del valle encantado del Baztan-Bidasoa te ofrece privacidad y unos exteriores de ensueño, en una finca donde todos los detalles están cuidados."},
 "eu":{"seo_t":"Ezkontzak Nafarroan — Finca Okalarre | Ezkontzak eta ekitaldiak naturan",
       "seo_d":"Ezkontzak eta ekitaldiak naturan, Baztan-Bidasoa haranean. Erabateko pribatutasuna, ametsetako kanpoaldeak eta ordutegi mugarik gabeko ospakizuna.",
       "hero_t":"Ezkontzak eta ekitaldiak naturan",
       "hero_sub":"Baztan-Bidasoa harana sorginduaren gailurretan dagoen paraje natural paregabea. Erabateko pribatutasuna, ametsetako kanpoaldeak eta ordutegi mugarik gabeko ospakizuna.",
       "anchor":"Ospatzea merezi duten zenbat gauza zoragarri gertatzen ote zaizkie maite ditugun pertsonei? Asko… Ziur gaude Okalarre dela gertakari berezi horietako bat behintzat ospatzeko lekurik aproposena.",
       "intro":"Baztan-Bidasoa harana sorginduaren gailurretan dagoen paraje natural paregabe batek pribatutasuna eta ametsetako kanpoaldeak eskaintzen dizkizu, xehetasun guztiak zainduta dauden finca batean."},
 "fr":{"seo_t":"Mariages en Navarre — Finca Okalarre | Mariages et événements en pleine nature",
       "seo_d":"Mariages et événements en pleine nature, dans la vallée du Baztan-Bidassoa. Intimité totale, extérieurs de rêve et célébration sans limite d'horaire. À 15 min d'Irun.",
       "hero_t":"Mariages et événements en pleine nature",
       "hero_sub":"Une enclave naturelle exceptionnelle sur les hauteurs de la vallée enchantée du Baztan-Bidassoa. Intimité totale, extérieurs de rêve et une célébration sans limite d'horaire.",
       "anchor":"Combien de choses exceptionnelles arrivent aux personnes qui nous sont chères et qui méritent d'être fêtées ? Un grand nombre… Nous sommes convaincus qu'Okalarre est le lieu parfait pour fêter au moins un de ces événements si spéciaux.",
       "intro":"Une enclave naturelle exceptionnelle sur les hauteurs de la vallée enchantée du Baztan-Bidassoa vous offre intimité et des extérieurs de rêve, dans un domaine où tous les détails sont soignés."},
 "en":{"seo_t":"Weddings in Navarre — Finca Okalarre | Weddings & events in pure nature",
       "seo_d":"Weddings and events in pure nature, in the Baztan-Bidasoa valley. Total privacy, dreamlike outdoor spaces and a celebration with no time limit. 15 min from Irun.",
       "hero_t":"Weddings and events in pure nature",
       "hero_sub":"An exceptional natural enclave on the heights of the enchanted Baztan-Bidasoa valley. Total privacy, dreamlike outdoor spaces and a celebration with no time limit.",
       "anchor":"How many exceptional things happen to the people we love that deserve to be celebrated? So many… We are certain that Okalarre is the perfect place to celebrate at least one of those truly special moments.",
       "intro":"An exceptional natural enclave on the heights of the enchanted Baztan-Bidasoa valley offers you privacy and dreamlike outdoor spaces, on an estate where every detail is cared for."},
}
